# Generated by Django 2.1.7 on 2020-05-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200511_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', models.CharField(default='ABOUT US', max_length=50, null=True)),
                ('small_desc1_headings', models.CharField(blank=True, max_length=100, null=True)),
                ('headings_desc1', models.TextField(null=True)),
                ('pics_headings', models.CharField(default='MY name', max_length=20, null=True)),
                ('admin_pics', models.ImageField(default=' profilpics.png', max_length=200, null=True, upload_to='')),
                ('desc2_admin', models.TextField(null=True)),
                ('small_desc2_admin', models.CharField(blank=True, max_length=100, null=True)),
                ('partners', models.IntegerField(default='0', null=True)),
                ('projects_done', models.IntegerField(default='0', null=True)),
                ('meetings', models.IntegerField(default='0', null=True)),
                ('happy_clients', models.IntegerField(default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aboutwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_at', models.TextField(blank=True, max_length=50, null=True)),
                ('good_at_percentage', models.IntegerField(blank=True, default='20', null=True)),
                ('works', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.About')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_images', models.ImageField(max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackgroundImage3', models.ImageField(null=True, upload_to='')),
                ('headings', models.CharField(default='CONTACT US', max_length=50, null=True)),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('small_desc1_headings', models.CharField(blank=True, default='WHERE I WORK', max_length=100, null=True)),
                ('small_desc2_subheadings', models.CharField(blank=True, default="I'd love your feedback!", max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='Lagos, NIGERIA', max_length=20, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facebookurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookUrl', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUrl', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedinUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedinUrl', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinterestUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinterestUrl', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackgroundImage2', models.ImageField(null=True, upload_to='')),
                ('headings', models.CharField(default='PORTFOLIO', max_length=50, null=True)),
                ('small_desc1_headings', models.TextField(blank=True, default='MY WORK', max_length=100, null=True)),
                ('small_desc2_subheadings', models.CharField(blank=True, default='Here are some of my work. Click on the image to view', max_length=300, null=True)),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_links', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SnapchatUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapchatUrl', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterUrl', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
