# Generated by Django 2.1.7 on 2020-05-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200529_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimages',
            name='portlink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Portfolio'),
        ),
    ]
