# Generated by Django 3.0.5 on 2020-06-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_portfolioimages_portlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimages',
            name='portlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Portfolio'),
        ),
    ]
